### ISSUE TITLE
New PyPi Release

### ISSUE THREAD

**Issue by Adminiuga** [zigpy/zigpy#104]
@rcloran Any chance you could publish a new Zigpy & Bellows release ?
We have a few important changes we would like to get into Hass 0.85 before the cutover date for beta. I understand it is a holiday season and don't want to steal too much of anyone's time, just need to know if it would be possible, otherwise I need to revert a few merged changes to hass prior the hass beta.

**Comment by Hedda** [comment]
@AndreasBomholtz do you have access and permission to do zigpy & bellows releases?

Perhaps a new PyPi release of zigpy-xbee as well? https://github.com/zigpy/zigpy-xbee

**Comment by AndreasBomholtz** [comment]
@Hedda No, i don't :(

**Comment by Hedda** [comment]
@AndreasBomholtz too bad. Would be a good idea if a "Zigpy Team" had access and permission?

**Comment by AndreasBomholtz** [comment]
Yes it would.

**Comment by Adminiuga** [comment]
I second that :)

**Comment by frog32** [comment]
If that takes too long we could also change the dependency in homeassistant and switch back as soon as the official release is out. Similar to https://github.com/home-assistant/home-assistant/commit/c89dade6193bcdbfec877fdaff941cd7ca300892 but without a fork on github just the pypi package.

**Comment by Hedda** [comment]
Submitted a separate issue request with #113 for those who wish to +1 or discuss a future "Team Zigpy"

https://github.com/zigpy/zigpy/issues/113

**Comment by Hedda** [comment]
@rcloran please push a new Zigpy release version to PiPy for use by Hass.io / Home Assistant

https://pypi.org/project/zigpy/
