### ISSUE TITLE
[REQUEST] ThirdReality (3reality) OTA provider for Third Reality branded Zigbee devices

### ISSUE THREAD

**Issue by Hedda** [zigpy/zigpy#1078]
Heard that [Third Reality (3reality)](https://www.3reality.com) joined "Works with Home Assistant"/"Works via Zigbee with Home Assistant" partner program.

https://www.home-assistant.io/blog/2022/10/13/third-reality-partner/

https://www.home-assistant.io/blog/2022/07/12/partner-program/

The first open latter question is if the [Third Reality, Inc.](https://www.3reality.com) as a company provides Zigbee OTA firmware update images for its devices?

https://www.3reality.com

The Follow-up question to that or rather an open letter feature request is if [Third Reality, Inc.](https://www.3reality.com) as a company is willing to spare development time to add a publicly available OTA (Over-The-Air) Provider Server or Repository where it publishes/hosts Zigbee firmware update image files for its devices as well as contribute some OTA Provider downloader code for this [zigpy library](https://github.com/zigpy/zigpy)?

https://www.home-assistant.io/integrations/zha#ota-firmware-updates

https://github.com/zigpy/zigpy/blob/dev/README.md#zigbee-device-ota-updates

As [Third Reality, Inc.](https://www.3reality.com) as a company probably do not know yet, zigpy is the Zigbee framework and hardware radio API/CLI abstraction code library that is used by Home Assistant's ZHA integration as well as a few other popular home automation software as a dependency in their Zigbee implementations and providing a "3reality Zigbee OTA provider" and matching downloader code support for Zigbee devices from [ThirdReality (3reality)](https://www.3reality.com/) in this zigpy library could potentially enable much easier OTA firmware upgrades for end-users of those in the future, and include; [ZHA integration](https://www.home-assistant.io/integrations/zha) for Home Assistant today, as well as probably [Zigbee plugin for Domoticz](https://www.domoticz.com/wiki/ZigbeeForDomoticz) (e.i. the [Domoticz-Zigbee](https://github.com/zigbeefordomoticz/Domoticz-Zigbee) project) and the [official Zigbee Plugin developed by Jeedom SAS](https://market.jeedom.com/index.php?v=d&p=market_display&id=4050) (i.e. the [Zigbee plugin for Jeedom](https://doc.jeedom.com/en_US/plugins/automation%20protocol/zigbee/)) in the future.

If Third Reality (3reality) already provide a  publicly available OTA (Over-The-Air) Provider Server or Repository where it publishes/hosts Zigbee firmware update image files then all that should be missing is an OTA provider code in zigpy.

Please see zigpy's existing OTA provider code ([provider.py](https://github.com/zigpy/zigpy/blob/dev/zigpy/ota/provider.py)) in Python which includes the URL links as source and downloader code for Zigbee OTA firmware image files for direct download:

https://github.com/zigpy/zigpy/blob/dev/zigpy/ota/provider.py

https://github.com/zigpy/zigpy/tree/dev/zigpy/ota

That is, this zigpy library would need a new "Third Reality OTA Firmware provider" section in that OTA provider code ([provider.py](https://github.com/zigpy/zigpy/blob/dev/zigpy/ota/provider.py)) to handle image download for Third Reality (3reality) OTA firmware update image files, (please see the "Skeleton OTA Firmware provider" for reference, as well as for referencing also studying [provider.py](https://github.com/zigpy/zigpy/blob/dev/zigpy/ota/provider.py) to also look at the other OTA providers that already have different code sections to handle the download of OTA files, such as; IKEA, INOVELLI, SONOFF, and LEDVANCE.

https://github.com/zigpy/zigpy/blob/dev/README.md#zigbee-device-ota-updates

Hopefully Third Reality will consider setting up an OTA provider server or creating a dedicated repository for all officially released Zigbee OTA files for Third Reality branded Zigbee devices?  

That way it will be a single trusted and official primary source of official Zigbee OTA files released by Third Reality, and that OTA provider source repository with your Zigbee OTA files could not only be used by zigpy as it could also be reused by other Zigbee implementations independently (both other open-source implementations as well as closed source and proprietary implementations).

Maybe also consider copying concept of `index.json` with metadata on all files like Koenkk repository has to make scripting easier:

https://github.com/Koenkk/zigbee-OTA/blob/master/index.json

zigpy and ZHA does not yet use this or other OTA Index files but [Zigbee2MQTT](https://www.zigbee2mqtt.io/) allows users to use it locally as described here:

https://github.com/Koenkk/zigbee2mqtt.io/blob/develop/docs/guide/usage/ota_updates.md#local-ota-index-and-firmware-files

and discussion in relation to zigpy implementation here:

https://github.com/zigpy/zigpy/issues/535

And of course `README.md` file which among other things could contain some basic information on how to update those:

https://github.com/Koenkk/zigbee-OTA/blob/master/README.md

Perhaps also as keeping some kind of `CHANGELOG.md` with changelog release history for each device firmware version:

https://github.com/Koenkk/Z-Stack-firmware/blob/master/coordinator/Z-Stack_3.x.0/CHANGELOG.md

PS: By the way, please also see this somewhat related discussion regarding here Koenkk zigbee-OTA repository -> https://github.com/zigpy/zigpy/issues/535

**Comment by pipiche38** [comment]
great news, and happy to integrate Third Reality  objects to the Zigbee for Domoticz plugin

**Comment by puddly** [comment]
Implemented in #1096

**Comment by Hedda** [comment]
@hwzolin FYI, puddly is working on standard for "Generic OTA providers" + a new JSON format schema:

https://github.com/zigpy/zigpy/wiki/OTA-Information-for-Manufacturers

  "**_This allows for new providers to be added to zigpy without extra code. This also allows for manufacturers to distribute test feed URLs to customers without deploying them globally._**"

This feature will be introduced via this new pull request that is still a work-in-progress. Please see ->  https://github.com/zigpy/zigpy/pull/1165
