### ISSUE TITLE
Should we replace monotonic time with coarse monotonic time

### ISSUE THREAD

**Issue by dmulcahey** [zigpy/zigpy#1100]
https://github.com/zigpy/zigpy/blob/2d24c014a93f2e79605620497c710265f9b2865a/zigpy/application.py#L572

See the discussion here: https://github.com/home-assistant/core/pull/81257

**Comment by puddly** [comment]
I tested this unscientifically on every platform I have and can't seem to replicate the issue:

```
     |  time()  |  coarse  |  monotonic
-----+----------+----------+-----------
XU4  |  7.97µs  |  7.08µs  |  7.87µs
CM4  |  0.21µs  |  0.30µs  |  0.21µs
x86  |  1.33µs  |  0.22µs  |  1.32µs
ARM  |  0.12µs  |  0.22µs  |  0.12µs
```

I don't think it's a problem for now.
