### ISSUE TITLE
[Enhancement] delete old tables

### ISSUE THREAD

**Issue by mdeweerd** [zigpy/zigpy#1127]
As I was checking the cache tables, I found that I have `attributes_cache_v7` up to `attributes_cache_v10`

And looking more closely, this is also the case for other tables (neighbors_v5, neigbors_v6, etc).

I suppoe that these tables could be cleaned up at some point to make the zigbee database slightly smaller.

**Comment by puddly** [comment]
Indeed they can. The purpose of the versioned tables is to permit Home Assistant upgrades/downgrades without losing the database and for schema migrations. We can probably just keep the last two versions.

**Comment by mdeweerd** [comment]
Yes, I think two versions are enough.
