### ISSUE TITLE
TS0601 _TZE200_aoclfnxz temp calibration

### ISSUE THREAD

**Issue by deennoo** [zigpy/zigpy#1141]
Using this thermostat on zigpy doesn't allow to make Temperature calibration

Following this topic : 

[TS0601 _TZE200_aoclfnx](https://community.home-assistant.io/t/zha-thermostat-moes-bht-002gclzb-alias-ts0601-tze200-aoclfnxz-local-temp-calibration/348193)

Using z2m allow this configuration.

is there a way to get it on zigpy ?

**Comment by puddly** [comment]
Temperature calibration is done by just adding/subtracting a value from the sensor readings in-software, this is out of scope for ZHA. You can do the same with a template sensor.
