### ISSUE TITLE
Ikea Styrbar OTA fail, new V recognized as older than current

### ISSUE THREAD

**Issue by Fettkeewl** [zigpy/zigpy#1153]
Hello !

I'm not a linux person so I do not know how nor dare do any changes in my Home Assistant OS 
via SSH. I am not able to solve my OTA upgrade of my Ikea Styrbar by editing and bypassing the **if ver >= self.version:** check
to allow my update to go through.

My Ikea Styrbar is at firmware v. 1.0.024 which apparently translates to a value of 65572 in HEX
and the new firmare is at v. 2.4.5 which translates to 581 in HEX.
Therefore I can't pass the check. 

Can't this check be changed to a numerical comparison which strips any dots following the first
so 2.4.5 becomes 2.45 and 1.0.024 becomes 1.0024
Then do an 
```
if 2.45(new) > 1.0024(current): 
    return true;
```

Snippet from **zigpy/zigpy/ota/__init__.py/**
```
def should_update(self, manufacturer_id, img_type, ver, hw_ver=None) -> bool:
        """Check if it should upgrade"""

        if self.key != ImageKey(manufacturer_id, img_type):
            return False

        if ver >= self.version:
            return False

        if (
            hw_ver is not None
            and self.image.header.hardware_versions_present
            and not (
                self.image.header.minimum_hardware_version
                <= hw_ver
                <= self.image.header.maximum_hardware_version
            )
        ):
´´´

**Comment by MattWestb** [comment]
I have updating one with the downgrading patch and was putting the firmware in local OTA file folder and disable IKEA OTA in the config and the device was updated after HA restart.
The updated device from device card `Firmware: 0x02040005` and one not updated `Firmware: 0x00010024`.

For the last OTA files IKEA have changing the new version to` 0x24040005` for getting it working with the 5 button and old motion sensor and its working OK. 

Our devs have verified that the firmware that the firmware inside the OTA file is OK and its working on the device but the metadata in the OTA file is wrong made (they have doing the same before for some lights).
IKEAs old GW is not using the version check they only flashing what the OTA index file is saying so they dont have that problem (Dirigera looks not doing any OTA updating of devices).

I dont knowing if dec numerical checks can being implanted without braking other devices OTA upgrades.
I also dont knowing if its possible patching the metadata in the OTA file without braking the signing of the file.

We have not fixing the battery renaming is showing 2 * the real reading for this firmware.

**Comment by Fettkeewl** [comment]
> I dont knowing if dec numerical checks can being implanted without braking other devices OTA upgrades.
Could it not be possible to add a numerical check only for this specific instance? 
something along the way of below in order to preserve the "normal function"
but to deal with this oddity.
```
if manufacturer_id == ikea and self.version == 65572 
  if 2.45(new) > 1.0024(current): 
    return true;
```

**Comment by MattWestb** [comment]
@TheJulianJES can you patching one file and posting it and we can testing if its working ?
I think its one more file (CWS3 ?) that is also wrong and cant being loaded or its have IKEA taking it back then it was not working OK (but i have save it).

**Comment by TheJulianJES** [comment]
Extract first:
[10078031-zingo_kt_styrbar_remote-2.4.5_modded_header.ota.ota.signed.zip](https://github.com/zigpy/zigpy/files/10580558/10078031-zingo_kt_styrbar_remote-2.4.5_modded_header.ota.ota.signed.zip)

Not sure this will work because of the signing though (or maybe the header isn't signed?)

**Comment by MattWestb** [comment]
Thanks Julian !!
I have normal IKEA OTA and also local OTA files and was putting the patched there restart HA and requesting update and its starting downloading it !!!
Only need waiting some hours to see if its passing the signing then its being downloaded or its throwing it and not flashing the firmware.

**Comment by MattWestb** [comment]
Two interesting lines:
```
2023-02-03 22:12:10.437 DEBUG (MainThread) [zigpy.zcl] [0x8F8E:1:0x0019] OTA upgrade_end handler for 'IKEA of Sweden Remote Control N2': status=Status.SUCCESS, manufacturer_id=4476, image_type=4555, file_version=33816581
2023-02-03 22:12:10.441 DEBUG (MainThread) [zigpy.zcl] [0x8F8E:1:0x0019] Sending reply: upgrade_end_response(manufacturer_code=4476, image_type=4555, file_version=33816581, current_time=0, upgrade_time=0)
```
And on the device card `Firmware: 0x02040005` but must reparing it then its using the V1 quirk.

So 95% is working only little more test must being done !!

Thanks @TheJulianJES  !!!

**Comment by TheJulianJES** [comment]
Also curious, can you check the ``zcl version`` reported? (old vs new firmware)

**Comment by MattWestb** [comment]
8 as aspected.

**Comment by MattWestb** [comment]
Found 2 interesting FCC papers.
E2112 Air sensor https://fccid.io/FHO-E2112
And some new remotes E2201, E2211,and E2213 is in the pipe and is using EZSP 7.X https://fccid.io/FHO-E2201/Letter/Model-Declaration-Letter-6321983.

So Styrbar is getting company of Symponisk 2 and Dimmer, Blind and shortcut buttons !!
