### ISSUE TITLE
test_periodic_scan_priority test failing

### ISSUE THREAD

**Issue by superherointj** [zigpy/zigpy#1171]
`test_periodic_scan_priority` test is failing at nixpkgs (https://github.com/NixOS/nixpkgs/pull/218993)

> FAILED tests/test_topology.py::test_periodic_scan_priority - AssertionError: assert 4 == 3

Error logs: https://termbin.com/qfu0l

Any suggestion on how to fix this? Or any hint if it is fine skipping this test?

Thanks.

**Comment by puddly** [comment]
What specific architecture is this failing with? I'm afraid I can't replicate this on both macOS and our CI tests with Python 3.8-3.11 on GitHub Actions' Linux runner.

Unrelated, but you can drop `python3.11-zigpy-cc`. The package will not be updated any further and it is incompatible with any recent release of zigpy.
