### ISSUE TITLE
[3.12.0b4] Enum changes

### ISSUE THREAD

**Issue by cdce8p** [zigpy/zigpy#1233]
The enum changes in `3.12` currently result in three test failures. (Tested with `3.12.0b4`)
```py
FAILED tests/test_quirks.py::test_read_attributes_uncached - TypeError: 'NoneType' object is not iterable
FAILED tests/test_zcl_clusters.py::test_time_cluster - TypeError: 'NoneType' object is not iterable
FAILED tests/test_zcl_clusters.py::test_ias_zone - TypeError: 'NoneType' object is not iterable
```

AFAICT it's related to how bitmap enums are deserialized. A simplified example
```py
import enum

class FixedIntType(int):
    def __new__(cls, *args, **kwargs):
        n = super().__new__(cls, *args, **kwargs)
        return n

class bitmap8(FixedIntType, enum.Flag):
    pass

print(bitmap8.from_bytes(b'\x00', 'little', signed=False))
```
https://github.com/zigpy/zigpy/blob/94a1603bd5b53b6bfa2781c13a9a0cf9f8e95c63/zigpy/types/basic.py#L195

#### Python 3.11.4
```py
bitmap8(0)
```

#### Python 3.12.0b4
```py
Traceback (most recent call last):
  File "/usr/src/test.py", line 14, in <module>
    print(bitmap8.from_bytes(b'\x00', 'little', signed=False))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/enum.py", line 742, in __call__
    return cls._create_(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/enum.py", line 870, in _create_
    for item in names:
TypeError: 'NoneType' object is not iterable
```

I've opened https://github.com/python/cpython/issues/106928. The original author (of the cpython change) asked for more details why this specific pattern is necessary. It would be awesome if someone with knowledge about the implementation could reply there so we can get this resolved.
/CC @puddly

**Comment by puddly** [comment]
Sure! In your linked example in the CPython repo, `bitmap8(0)` is actually enough to reproduce the issue: `from_bytes` is unrelated.

We used the bare `bitmap8` type (and not a subclass) in our codebase as a placeholder for where a bitmap type is expected but:

1. we either haven't implemented the specific one by further subclassing `bitmap8`
2. or the specification does not specify a specific type, just that it is an opaque bitmap of a known size

Restoring the Python 3.11 behavior would be the simplest solution. As a workaround, however, it looks like subclassing is now allowed for bitmap types so we could in theory resolve this by defining a `NONE = 0` default member within the base `bitmap` class, but this would not be compatible with any earlier version of Python.
