### ISSUE TITLE
changing the channel

### ISSUE THREAD

**Issue by martin3000** [zigpy/zigpy#1241]
I have a cc2652rb znp stick (slae.sh), used with ZHA in home assistant. 
I wanted to change the channel, because the current channel was very noisy.
I plugged all zigbee devices in and in home assistant I started the change of the channel. 
After 20s, it was done and all 60 devices were on the new channel.
I'm very surprised and happy!

**Comment by puddly** [comment]
I'm glad it worked!

Are there any devices that did not migrate?

**Comment by martin3000** [comment]
In the first moment, it looked like all devices migrated. But in the next morning, around 15 battery devices fell off or were in a zombie state and had to be re-paired.
So don't do the channel migration if you have more than 5 battery devices.
