### ISSUE TITLE
[Feature Request] Support of Aeotec Pico (Duo) Switch

### ISSUE THREAD

**Issue by CHTHSCH** [zigpy/zigpy#1313]
I would appreciate, if these two new products would be supported by the Zigbee Integration.

[ZGA002 - Aeotec Pico Switch](https://aeotec.com/products/Aeotec-Smartthings-Pico-Switch/)
[ZGA003 - Aeotec Pico Duo Switch](https://aeotec.com/products/Aeotec-Smartthings-Pico-Switch/)

**Comment by tube0013** [comment]
https://aeotec.freshdesk.com/support/solutions/articles/6000266747-setup-pico-switch-with-home-assistant

**Comment by CHTHSCH** [comment]
Thanks

In that case the list here [https://zigbee.blakadder.com/index.html](url) is outdated. Sorry for posting an irrelevant request.

**Comment by puddly** [comment]
ZHA supports any standard-compliant device out of the box so that list will never be complete: it's built from user-reported "it works for me" submissions.
