### ISSUE TITLE
[Feature Request] Support of Aeotec Pico Shutter

### ISSUE THREAD

**Issue by SmartLiving-Rocks** [zigpy/zigpy#1384]
Hello all

I have the Pico Shutter form Aeotec successfully paired with ZHA using Home Assistant. https://store.aeotec.com/products/pico-shutter-zigbee-zga004

## Change and Check Attribute: e.g. Switch Mode
I would like to know how I can change the switch type to Momentary switch. [In the manual](https://aeotec.freshdesk.com/helpdesk/attachments/6195353076), it says that the 0xFD00 attribute needs to be changed to 0x01

![bd1ebb1d30632f702f625956e7ea9dfd047a5f6b_2_1160x1000](https://github.com/zigpy/zigpy/assets/76279896/61531ba9-9c31-482f-afc9-2a13998c8485)

## ZHA in Home Assistant 
If I check the device configuration I find the right section but I am not able to change anything. 

![53d06ce89825a3aedae9138c4e3ba67f0cae7494_2_1098x1000](https://github.com/zigpy/zigpy/assets/76279896/229cd324-3c3a-4b17-9062-a5f9fcf23340)

## Switch: Inverte Mode
In the UI there are also two switches. If I switch it on it automatically goes back to `off`. I am not sure if that is the right behavior. 

Thanks for your advise

**Comment by puddly** [comment]
Can you open an issue here instead https://github.com/zigpy/zha-device-handlers/ ?

This repository is for zigpy, which does not implement manufacturer-specific functionality.
