### ISSUE TITLE
missing unitz use quirks v2

### ISSUE THREAD

**Issue by GitforZhangXL** [zigpy/zigpy#1466]
With zha quirks v2, the code looks like this, but the generated entity is missing units
```
(
    QuirkBuilder(
        "Tuya", "DDM02"
    )
    .skip_configuration()
    .adds(ElectricalMeasurement.cluster_id,endpoint_id=8)
    .sensor(ElectricalMeasurement.AttributeDefs.rms_current_ph_b.name, device_class=SensorDeviceClass.CURRENT,cluster_id=ElectricalMeasurement.cluster_id,endpoint_id=8)
    .add_to_registry()
)
```

"device_class" will not contain the unit
https://github.com/zigpy/zigpy/blob/754b1cde78eb90dd21c11f50b4c9c39bbe936d99/zigpy/quirks/v2/__init__.py#L257-L271

zigpy==0.66
zha== 0.0.32
zha-quirks== 0.0.121
home-assistant core==2024.9.0

![missing](https://github.com/user-attachments/assets/5b9f87e1-a6d9-4418-926e-ee3940040363)

**Comment by TheJulianJES** [comment]
This should be fixed with newer zigpy and Home Assistant versions.
