### ISSUE TITLE
Why zigpy package is named zigpy-homeassistant ?

### ISSUE THREAD

**Issue by doudz** [zigpy/zigpy#190]
Why zigpy package is named zigpy-homeassistant ?
zigpy-homeassistant name suppose it's a special release of zigpy for homeassistant and since both zigpy and zigpy-homeassistant exists on pypi, it's a bit confusing

I'm working on zigpy-zigate, should I rely on zigpy or zigpy-homeassistant ?

**Comment by dmulcahey** [comment]
use the homeassistant variant. There are 2 because we don't have access to publish the original to PyPi

**Comment by doudz** [comment]
oh, so sad
I understand, thanks
