### ISSUE TITLE
light or switch ?

### ISSUE THREAD

**Issue by Nemesis24** [zigpy/zigpy#241]
hello !

I've got a question (issue ??) about two xiaomi devices...
1: lumi.relay.c2acn01
2: lumi.ctrl_ln2.aq1

the first one give me 2 "lights" in home assistant
the second give me 2 "switches" in home assistant

in my case i don't know if i'm alone the first one must give me 2 switches (motor), and the second two lights.

Is there a way to define the type (light or switch) ? when adding device for example ?

for the moment i use 

```
light:
  - platform: switch 
```

to convert switch in light.

Thank you.

**Comment by Adminiuga** [comment]
This is really homeassistant question. It is being detected as I get probably because of endpoint device type. You can override it via configuration.yaml. see https://community.home-assistant.io/t/zha-zigbee-tested-devices-please-add-your-device-results/17718/384?u=quatuor for details.

**Comment by Nemesis24** [comment]
Ok thank you exactly what i need !!!!
Thank you very much.
