### ISSUE TITLE
Port ZSmartSystems ZigBee Java library supporting multiple dongles  

### ISSUE THREAD

**Issue by Gamester17** [zigpy/zigpy#25]
As I understand ZSmartSystems ZigBee Java library aims to do what Zigpy and bellows does but in Java:

https://github.com/zsmartsystems/com.zsmartsystems.zigbee

Just suggestion to read and learn from their mistakes and success, and port over tweaks, etc.

FYI; this library was developed by @cdjackson who also developed the OpenHAB binding for ZigBee:

https://github.com/openhab/org.openhab.binding.zigbee/

https://github.com/cdjackson

http://www.cd-jackson.com

**Comment by rcloran** [comment]
https://www.eclipse.org/legal/eplfaq.php#GPLCOMPATIBLE

I'm going to close this issue out. There's no point where I could say it was "done", so I don't really see the point in keeping it open.
