### ISSUE TITLE
Forming a new ZigBee Network

### ISSUE THREAD

**Issue by junsaw** [zigpy/zigpy#293]
I am trying to create a new ZigBee network, when I issue the command below this is the error I get.  Is there a process to create the database file. 

bellows --device /dev/ttyUSB1 form
Usage: bellows form [OPTIONS]
Try "bellows form --help" for help.

Error: Invalid value for "-D" / "--database": File "/root/.config/bellows/app.db" does not exist.

Please note: I do not have homeassistant installed I am trying to leverage the python Library directly.

**Comment by Adminiuga** [comment]
This belongs to `bellows`. Create `/root/.config/bellows/` folder and try again.

**Comment by junsaw** [comment]
I tried that and its still giving the same error. 

ls -al /root/.config/
bellows/ procps/ 


bellows ^C
root@junior-raspblnx01-edge:~ # bellows --device /dev/ttyUSB1 devices
Usage: bellows devices [OPTIONS]
Try "bellows devices --help" for help.

Error: Invalid value for "-D" / "--database": File "/root/.config/bellows/app.db" does not exist.

**Comment by Adminiuga** [comment]
form the network first.
