### ISSUE TITLE
[SUGGESTION] Migrate zigpy-cc repository to upstream zigpy organization? 

### ISSUE THREAD

**Issue by Hedda** [zigpy/zigpy#295]
@Adminiuga & @dmulcahey can I suggest that you please consider talking to @sanyatuning about the possibility of you joining the zigpy organization @ https://github.com/zigpy/ and maybe also having your zigpy-cc repository here on GitHub moved to the zigpy organization @ https://github.com/zigpy/ so that the mainstream copy of this repo will stay there as its upstream instead and owned by the upstream zigpy organization? 

That way all developers that are members in the zigpy organization can have write access to one or more projects that it own for collaboration as a community? Hope that you could all come to an agreement that will make everyone happy with continuing with working on the  zigpy-cc repository together without getting offended by any ownership conflicts.

PS: Also posted same suggestion on zigpy-cc repository by @sanyatuning here https://github.com/sanyatuning/zigpy-cc/issues/13

**Comment by sanyatuning** [comment]
Done!
