### ISSUE TITLE
[SUGGESTION] Migrate zigpy-zigate repository to upstream zigpy organization? 

### ISSUE THREAD

**Issue by Hedda** [zigpy/zigpy#296]
@Adminiuga & @dmulcahey can I suggest that you please consider talking to @doudz about the possibility of him joining the zigpy organization @ https://github.com/zigpy/ and maybe also having his zigpy-zigate repository here on GitHub moved to the zigpy organization @ https://github.com/zigpy/ so that the mainstream copy of this repo will stay there as its upstream instead and owned by the upstream zigpy organization? 

That way all developers that are members in the zigpy organization can have write access to one or more projects that it own for collaboration as a community? Hope that you could all come to an agreement that will make everyone happy with continuing with working on the zigpy-zigate repository together without getting offended by any ownership conflicts.

PS: I also posted same suggestion on zigpy-zigate repository by @doudz here https://github.com/doudz/zigpy-zigate/issues/17

**Comment by doudz** [comment]
Done
