### ISSUE TITLE
[REQUEST] Unified capability and method for handling radio serial-port disconnects and reconnects

### ISSUE THREAD

**Issue by Hedda** [zigpy/zigpy#320]
It is possible to implement some type of shared unified capability and method in zigpy for general handling serial-port disconnects and reconnects / recovery of disconnection from the radio transceiver over serial communication?

That is, can all or some code for this be shared in zigpy and among all the radio libraries for zigpy or does each radio library for zigpy need to handle serial-port disconnects and reconnects separately on their own using different methods? 

Anyway, my main point of this common feature concept I would like to see achieved is that zigpy and all the radio libraries for zigpy should somehow always be able to reconnect to the Zigbee coordinator adapter after an unplanned disconnect as well as be able to fully recover the connection after reconnecting.

I believe that being able to handle radio serial-port disconnects and reconnects could be one of many small improvements that can help make zigpy implementations feel a little more stable all in all.

If I understand it correctly that both [zigpy-cc](https://github.com/zigpy/zigpy-cc) radio library by @sanyatuning and [zigpy-zigate](https://github.com/doudz/zigpy-zigate) radio library by @doudz have now separately implemented automatic handling of serial-port disconnects and reconnect in slightly different ways through using similar code for their different solutions?

I guess the best solution was if zigpy and all radio libraries shared the exact same code for this feature?

- https://github.com/zigpy/zigpy
  - https://github.com/zigpy/bellows
  - https://github.com/zigpy/zigpy-cc
  - https://github.com/zigpy/zigpy-deconz
  - https://github.com/zigpy/zigpy-xbee
  - https://github.com/zigpy/zigpy-zigate
  - https://github.com/zha-ng/zigpy-znp
    - https://github.com/puddly/zigpy-znp

My own personal reason for requesting this feature is that it is needed when using ser2net and socat to use the serial device over the network and the network goes down for whatever reason.  The problem there today is if the network temporarily goes down today then zigpy does not seem to be able to reconnect to recover the connection for some Zigbee USB adapters, forcing the user to resort to restarting Home Assistant. 

Another problem scenario is if the user accidentally unplugs the Zigbee USB adapter when running. So I think that you can best test this by simply unplugging the Zigbee coordinator adapter and then plug it back in after a few minutes so see if it always recovers or if a restart of HA is needed.

Such as networked setup is otherwise relatively common if one does not want the radio close to Home Assistant, so I am not alone with using such a ser2net and socat setup, just see: 

https://www.zigbee2mqtt.io/how_tos/how_to_connect_to_a_remote_adapter.html

Example of a real-world scenario would be if you have Home Assistant and running on a virtual machine on your NAS with UPS-backup-power-supply but have your Zigbee coordinator adapter installed somewhere else in your house on a Raspberry Pi without UPS-backup-power-supply then a power-outage will cause the Raspberry Pi to reboot and maybe also any network switch that you have in between.

I think that preferable it should be able to try to recover at least once every 60-seconds and that recovery should still be possible after as much as 10-minutes (or more) because that is reasonably how long a reboot can take after a short power outage.

PS: Related but off-topic question: Should it not be possible to only restart ZHA? I could not at least figure out how to only restart ZHA in Home Assistant without restarting Home Assistant as a whole.

**Comment by Adminiuga** [comment]
Closing this. all radios now support disconnects.
