### ISSUE TITLE
[SUGGESTION] Move back to only using the PyPI-project "zigpy" and stop using the PyPI-project "zigpy-homeassistant"

### ISSUE THREAD

**Issue by Hedda** [zigpy/zigpy#351]
Please consider moving back to only using the PyPI-project "zigpy" for the zigpy library package and stop using the PyPI-project "zigpy-homeassistant" to distribute the zigpy library package.

I understand that the active PyPI projects being named "zigpy-homeassistant", "zigpy-xbee-homeassistant", and "bellows-homeassistant" can be confusing to new developers, especially to those who wish to use zigpy and bellows without Home Assistant as they might think that Home Assistant is a requirement for using these libraries.

- https://pypi.org/project/zigpy/
- https://pypi.org/project/zigpy-homeassistant/

Note! This request is indirectly related to my suggestion to rename bellows -> https://github.com/zigpy/bellows/issues/215

PS: @rcloran @Adminiuga & @damarco Regardless of above it is probably also a good idea if you could and would make a few more zigpy developers shared co-owner/co-author/co-maintainers of the "zigpy" and "zigpy-homeassistant" as well as "bellows" and "bellows-homeassistant" or "zigpy-xbee" and "zigpy-xbee-homeassistant" projects on PyPI. That could help remove personal pressure as well as explicit dependence on specific individuals.

- https://pypi.org/project/zigpy/
  - https://pypi.org/project/zigpy-homeassistant/
- https://pypi.org/project/zigpy-xbee/
  - https://pypi.org/project/zigpy-xbee-homeassistant/
- https://pypi.org/project/bellows/
  - https://pypi.org/project/bellows-homeassistant/

Maybe you can consider making ex. @dmulcahey and @puddly maintainers or those projects as well?

I have not seen that @damarco and @AndreasBomholtz as active with zigpy related projects for quite some time, however, @Adminiuga @dmulcahey and @puddly all seem to be very active (considering these are all still just hobby projects).

**Comment by Hedda** [comment]
For reference, see related https://github.com/zigpy/zigpy/pull/363

**Comment by Adminiuga** [comment]
Fixed in 0.20.0
