### ISSUE TITLE
[REQUEST] Allow setting strength of "TX Power" configuration for radios with Power Amplifier (PA)

### ISSUE THREAD

**Issue by Hedda** [zigpy/zigpy#372]
Allow user to change/set "TX Power" for Power Amplifier (PA) if available option in the radio library?

This is a follow up to the requests https://github.com/zigpy/zigpy-cc/issues/33 and https://github.com/zha-ng/zigpy-znp/issues/11

If and when radio libraries allow configuration of custom "TX Power" (TX PWD) settings on radio modules which feature integrated or external Power Amplifier (PA) then Zigpy too needs to be able to allow users to set a custom "TX Power" setting for that radio module via the software using zigpy, like from Home Assistant's ZHA UI configurations, or?

It should be noted that even if radio modules have this type of "TX Power" feature and a function to set a custom configuration, they will also have a default setting which is always automatically used if no custom "TX Power" setting is asked to be set.

PS: As I understand, in the case of TI CC chips, those have their maximum dBm hardcoded within safe limits so that there is no way to destroy the HW through these settings. It is just that depending on the frequency band, too high dBm values may not be legal outdoors and/or indoors depending on your country regulations, and therefore TI has set a low default value so that it is legal in all countries if one does not increase the values.

**Comment by Adminiuga** [comment]
Unless this could be configured across all zigpy supported radios, I'd leave it to the radio lib implementation. Could be implemented with pending changes in zigpy. For example take a look at https://github.com/zigpy/bellows/commits/new-zigpy-init/dev  which implement EZSP config customization.

**Comment by Hedda** [comment]
FYI, apparently @puddly has already enabled this in [3f6968d](https://github.com/zha-ng/zigpy-znp/commit/3f6968d7af53e15d893d92240136bf93ef42f7ed) for the zigpy-znp radio library.

**Comment by Hedda** [comment]
As I understand this is related to https://github.com/zigpy/zigpy/issues/381 as "TX Power" is an extension that maybe not all radio libraries will use but zigpy / ZHA need to be able permit and config it.
