### ISSUE TITLE
[REUQEST] Allow option to disable and enable LED/LEDs on adapter

### ISSUE THREAD

**Issue by Hedda** [zigpy/zigpy#384]
Option to configure settings for disabling and enabling LED/LEDs on the Zigbee radio adapter/dongle.

Requested for CC2531 dongle by @Yevgenium in https://github.com/zigpy/zigpy-cc/issues/42

@sanyatuning I understand this is related to #381 as another example of an optional extension?

**Comment by sanyatuning** [comment]
I think, yes

**Comment by Adminiuga** [comment]
I'm closing this. IMO, unless a feature could be implemented for all current radios, it should not be in zigpy. 
LED control in this particular case is for specific radio and specific board/model, so should not be part of zigpy.
