### ISSUE TITLE
[REQUEST] Feature to migrate from one Zigbee coordinator adapter hardware type to a other

### ISSUE THREAD

**Issue by Hedda** [zigpy/zigpy#410]
The idea came from developer discussion between @Adminiuga & @puddly in https://github.com/zha-ng/zigpy-znp/issues/10

Would possible to script a "backup and restore" migration feature/function built into zigpy that allow users to relatively easily migrate from one Zigbee coordinator hardware adapter to a other type of Zigbee coordinator hardware adapter if use same radio library or maybe even if they are not using the same radio library?

Migrations such as these could become common as new more powerful adapters become available:

- HUSBZB-1 (bellows) adapter -> Zig-a-zig-ah / ZZH (zigpy-znp) adapter
- CC2530 (zigpy-cc) adapter -> ZiGate WiFi (zigpy-zigate) adapter
- CC2531 (zigpy-cc) adapter -> ConBee II (zigpy-deconz) adapter

Would still be an awesome feature even if it was only possible to migrate within the same radio type:

- LAUNCHXL-CC26X2R1 (zigpy-znp) adapter -> LAUNCHXL-CC1352P-2 (zigpy-znp) adapter
- CC2531 (zigpy-cc) adapter -> Zig-a-zig-ah / ZZH (zigpy-cc) adapter
- ConBee / RaspBee (zigpy-deconz) adapter -> ConBee II (zigpy-deconz) adapter

Would really be an awesome feature to have if could be made user-friendly for integration like ZHA!

**Comment by Adminiuga** [comment]
Won't be possible for a regular user and not between all adapters. e.g.  I don't know if it is possible to read the network key from EZSP based radios. 
ATM I'd recommend implementing it at radio lib level, similar feature as deCONZ backups/restoration.
