### ISSUE TITLE
AttributeError: module 'zigpy.types' has no attribute 'HexRepr' with dev branch

### ISSUE THREAD

**Issue by pipiche38** [zigpy/zigpy#453]
Looks like HexRepr class definition has been removed from zigpy.types in dev branch.

Does that mean it has to be defined localy where we need to use , or an other class must be used ?

```
class HexRepr:
    def __repr__(self):
        return ("0x{:0" + str(self._size * 2) + "x}").format(self)

    def __str__(self):
        return ("0x{:0" + str(self._size * 2) + "x}").format(self)
```

**Comment by pipiche38** [comment]
Ok. I'm lost I'll wait that the guy in charge of the Zigpy_Zigate to update its code!

**Comment by Adminiuga** [comment]
@pipiche38 Don't wait on him. If you know how to fix it, then submit a PR. Otherwise use pinned versions for zigpy and zigpy-zigate in your code.
