### ISSUE TITLE
Can signature bring model and manufacturer 

### ISSUE THREAD

**Issue by pipiche38** [zigpy/zigpy#464]
Would it be possible that signature method bring up the Model ( 0x0000/0x0005 ), Manufacturer Code ( from Node Descriptor)  and Manufacturer Name ( 0x0000/0x0004)

Those information will be important for the above layers using the libraries.

**Comment by Adminiuga** [comment]
what are you asking?

**Comment by pipiche38** [comment]
when using device.get_signature() I got a number of device information like EndPoint, Cluster_in, Cluster_out, but it would be great to get in the returned data structutre to have additional information like Mode, Manuf code Manuf Name ...
