### ISSUE TITLE
[QUESTION] Should it be possible to mix and match any combination of zigpy and radio libraries branches?

### ISSUE THREAD

**Issue by Hedda** [zigpy/zigpy#484]
Should it generally always be possible to mix and match any combination of any zigpy branch and any branch of any radio library?

Should all radio libraries and all their branches work with both zigpy master branch as well as with zigpy dev branch?

If they all did then shouldnät that make the testing of both zigpy dev branch with radio library master branch and the vice versa?

This is really just a follow up on https://github.com/zigpy/zigpy-zigate/issues/40 and https://github.com/zigpy/zigpy/issues/453 where zigpy-zigate could not be used with zigpy dev branch.

@pipiche38 posted these questions in https://github.com/zigpy/zigpy/pull/479 but it was off-topic there so just reposting that questioning for discussion here:

"**_Should dev be compatible with zigpy/dev only or must it be compatible with zigpy/master ?_**"

"**_I think there is a general issue to be addressed in terms of compatibility across the various Radio libs._** "

**Comment by Adminiuga** [comment]
generally yes, but not always. Libraries do update the min required version.
