### ISSUE TITLE
Use python3.5+ await syntax

### ISSUE THREAD

**Issue by jonatanolofsson** [zigpy/zigpy#5]
Home assistant is dropping python3.4 support, so it's time to update the zigpy syntax to use the await syntax. This also improves the support to e.g. spot unawaited futures.

**Comment by rcloran** [comment]
Happy to do this when HA drops 3.4 support.

**Comment by jonatanolofsson** [comment]
It was dropped in October last year: https://home-assistant.io/blog/2017/10/06/deprecating-python-3.4-support/

**Comment by rcloran** [comment]
Nope. That was an announcement saying it will be dropped. https://github.com/home-assistant/home-assistant/blob/dev/tox.ini#L2

**Comment by Adminiuga** [comment]
I think it is reasonable to expect it will be dropped really soon, once [PR #12921 -- upgrade to aiohttp3](https://github.com/home-assistant/home-assistant/pull/12921) goes through.

**Comment by balloob** [comment]
The next release, 0.65, will bump the minimum version to Python 3.5.3

**Comment by AndreasBomholtz** [comment]
It is fixed in PR #31.
