### ISSUE TITLE
Posible to support cc2531 usb Dongle?

### ISSUE THREAD

**Issue by dzungpv** [zigpy/zigpy#54]
Now there are some solution to use cc2531 like https://github.com/Koenkk/zigbee2mqtt but it is not native with hass. So there is any way to make it work with cc2531, because it is very cheap ($10 from China). I have buy some and the tool to dev it but find no way to start.

**Comment by ciotlosm** [comment]
https://github.com/danielwelch/hassio-zigbee2mqtt

**Comment by Gamester17** [comment]
Could maybe port cc-znp? cc-znp is an interface for a host to communicate with TI CC253X Zigbee Network Processor(ZNP) over a serial port, this is used by zigbee-shepherd among other projects.

https://github.com/zigbeer/cc-znp
https://github.com/zigbeer/zigbee-shepherd/wiki
https://github.com/zigbeer/documents/tree/master/zigbee-shepherd

Could this be achieved with the a module for Z-Stack firmware for CC253x (like CC2530 and CC2531) used by zigbee-shepherd based projects like zigbee2mqtt?

zigbee-shepherd is an open source ZigBee gateway solution with node.js. It uses TI's CC253X wireless SoC as a zigbee network processor (ZNP), and takes the ZNP approach with cc-znp to run the CC253X as a coordinator and to run zigbee-shepherd as the host.

Source code as well as pre-built firmware for  Z-Stack firmware for CC253x is available for example:

https://github.com/zigbeer/documents/tree/master/zigbee-shepherd
https://github.com/Koenkk/Z-Stack-firmware
https://github.com/Koenkk/Z-Stack-firmware/tree/master/coordinator
https://github.com/Koenkk/zigbee2mqtt/wiki/Getting-started

**Comment by ericmiller777** [comment]
It would be nice to have it for the home assistant integrated menus.

**Comment by andriej** [comment]
+1, would love to see it in. hA

**Comment by Adminiuga** [comment]
Same as #85 closing this one to keep everything in one place.

**Comment by Gamester17** [comment]
@dzungpv @ciotlosm @ericmiller777 @andriej

FYI, sanyatuning started with CC2531 support for Zigpy here https://github.com/sanyatuning/zigpy-cc

Some more information about that can also be found here https://github.com/zigpy/zigpy/issues/85
