### ISSUE TITLE
Binding in zll

### ISSUE THREAD

**Issue by zoic21** [zigpy/zigpy#545]
Hello
I have some question about zll about binding. It's not work, device say it's ok I take binding but on state change it never send me device update.

If I force attributes update without cache it's ok I get current value.

I think in zll there is a trick to get aware of attribute update but I can't find it.

Thanks in advance

**Comment by Adminiuga** [comment]
Check how zha in home assistant does it.

**Comment by zoic21** [comment]
Thank I look on it and it's use force read attribute on repeat task... I will make that also.
