### ISSUE TITLE
PiZiGate + TS0601

### ISSUE THREAD

**Issue by Kermit79** [zigpy/zigpy#552]
Hello,
I bought a Tuya thermostatic valve (TS0601) and I would like to pair it with my Pizigate, but it doesn't work very well...
The pair is ok, but i can't read anything, and ZigPy doesn't create any entity.

I put the verbose mode, this is the log :
http://pastebin.fr/73875

This is my "ZigBee informations" :
http://pastebin.fr/73877

I'll also search, I'll keep you informed.

Thanks !

**Comment by Kermit79** [comment]
PS : I think zigpy-zigate is better than here, i posted overt there sorry !

**Comment by Adminiuga** [comment]
It is not zigpy nor zigpy-zigate issue. Tuya uses a proprietary protocol. I can only suggest not supporting vendors who do proprietary protocols just to lock you in. 

An effort to make it work is done in https://github.com/zigpy/zha-device-handlers/pull/538
