### ISSUE TITLE
Delayed switching (Tuya zigbee TS004x)

### ISSUE THREAD

**Issue by pjkersten** [zigpy/zigpy#601]
Hi,

I'm experiencing delay issues with Tuya TS004x remote control switches. After pressing a key, it takes 4-5 seconds before HA reacts. The ZigBee message itself is 'instantaneous' (using debug level logging), but HA's reaction isn't.

I suspect that discriminating between 'press' and 'long press' or 'double press' is the culprit as it would take some time, but this delay makes things next to unusable. I was not able to find anything useful in the code.

Any hints, suggestions on where to find the handling code / what I can do to enhance the UX (aka remove delays)?

Any help is appreciated.

TIA!

**Comment by Adminiuga** [comment]
debug log including zigbee message and homeassistant.core event fired.
I can confirm the delay, but apparently the delay is from the device itself, specially when you are doing double clicks

**Comment by pjkersten** [comment]
I've contacted the manufacturer. Hope they can shed some light on this.
