### ISSUE TITLE
Question about time cluster

### ISSUE THREAD

**Issue by zoic21** [zigpy/zigpy#676]
Hello,

I have a small question about time cluster and function ``handle_cluster_general_request`` like I see when device request time this function handle that calcul time from 1er janury 2000 00:00:00 than do a read :
https://github.com/zigpy/zigpy/blob/a1605a60a10645272c86030f634158ad224d51b6/zigpy/zcl/clusters/general.py#L536

Why I read and not write into cluster ? I think I don't understand really whati is the purpose of ``handle_cluster_general_request``.

Thank in advance for your response.

**Comment by Adminiuga** [comment]
Handle_cluster_general request is similar to handle_cluster_request() except it handles global/general request like read attributes, write attributes, report attributes etc. 
The devices on the network are reading time from the coordinator time cluster, therefore this one handles attribute_read request and replies with attribute_read_response.

I don't want devices to write the time so it doesn't handle any other ZCL general request commands.
