### ISSUE TITLE
Reach an Error asyncio.excepion.TimeoutError

### ISSUE THREAD

**Issue by markicos** [zigpy/zigpy#682]
Hello there i am having this problem when using the code example in https://github.com/zigpy/zigpy/issues/452#issuecomment-671441387 but i am reaching an exception.Timeout, i don`t know what i am doing wrong or if i miss some module.

![image](https://user-images.githubusercontent.com/44501063/109961325-1fa48800-7cea-11eb-8ed0-6895fa72e70c.png)

I am using conbee II with zigpy-deconz

Anyone can help?

**Comment by Adminiuga** [comment]
Belongs to zigpy-deconz.
Unknown how well serial ports work on windows.
It did not get a reply to the serial command send to the port. Is it correct port?

**Comment by MattWestb** [comment]
Shall the  https://github.com/zigpy/zigpy-znp/commit/f85c281b7fd335ff6658d02154999fcfa4832d99 also being done for all other radios so they is not getting the same problem that @puddly  was finding ??

**Comment by markicos** [comment]
Thank a lot to both of you, 

It is the correct port,
I downgraded the pyserial-asyncio and it works 👯,

**Comment by MattWestb** [comment]
Thanks great to hearing !! 
But your thanks shall going to our @puddly but perhaps @Adminiuga need adding the "patch" to the other radios so they is working OK on windows machine or waiting for the bug being fixed in the lib.
