### ISSUE TITLE
zigpy RPM packages/files for Fedora Linux distribution?

### ISSUE THREAD

**Issue by Hedda** [zigpy/zigpy#749]
Are there rpm zigpy library, zigpy radio, and zha-device-handlers (quirks) libraries/dependencies packaging for Fedora distribution?

https://github.com/zigpy

Saw @pipiche38 asking in regarding to getting zigpy for Domoticz-Zigpy in Domoticz on Fedora -> https://github.com/pipiche38/Domoticz-Zigpy/issues/27

Perhaps @dpocock or @FedericoCeratto is interested in porting package as read that they packaged domoticz-zigate for Debian:

https://danielpocock.com/domoticz-packaging-debian-ubuntu-raspbian-fedora/

 "_Federico Ceratto and I have been working on the Debian packaging of Domoticz, one of the leading free and open source home automation / smart home solutions. As there are a large suite of packages involved, I'm keen to find more people willing to collaborate on a parallel packaging for Fedora. Many of the enhancements we've made for Debian, such as the directory structure, are applicable across all GNU/Linux distributions_."

RPM “packaged” packages reference: 

https://fedoramagazine.org/rpm-packages-explained/

PS: Also started a discussion about the Domoticz-Zigpy plugin here -> https://github.com/zigpy/zigpy/discussions/750

**Comment by Adminiuga** [comment]
what's the point of this issue? Stop spamming people. This is python, what porting are you talking about.
