### ISSUE TITLE
New PyPi Release

### ISSUE THREAD

**Issue by cgarwood** [zigpy/zigpy#76]
Could we get a new release pushed to PyPi so Home Assistant's requirement can be updated?

**Comment by AndreasBomholtz** [comment]
@rcloran Can you make a new release?

**Comment by cgarwood** [comment]
Any updates? Seems like @rcloran hasn't been around much lately.

**Comment by AndreasBomholtz** [comment]
No, I have not heard anything from him.
So the only thing that I can do is to push it under a new name. Other then that, I do not know what to do.

**Comment by rcloran** [comment]
I'll push a new set of releases today.

**Comment by rcloran** [comment]
I do want to get #78 fixed first. Seems it shouldn’t be too hard.

**Comment by Gamester17** [comment]
Bump this to get a new release in PyPi with support for the newish Ikea Trådfri Plug. Thanks in advance!

**Comment by Hedda** [comment]
Please bump PyPi release now that both Aqara Magic Cube and Ikea Trådfri Plug been added

**Comment by Hedda** [comment]
Duplicate of #104 however the comments here from @Adminiuga might bare more weight
