### ISSUE TITLE
OTA Support for Salus

### ISSUE THREAD

**Issue by davet2001** [zigpy/zigpy#827]
I have started work on OTA support for Salus devices, PR #839.

The list of available firmware files is here:
https://eu.salusconnect.io/demo/default/status/firmware?timestamp=0

For comparison here is the one for ikea:
http://fw.ota.homesmart.ikea.net/feed/version_info.json

One thing I find different is that the list of available firmware from salus doesn't have a device ID that matches the numerical device ID coming from the ZHA device like the ikea and ledvance devices.  In the OTA code, those devices seem to be able to reference the FW by a numerical ID to know which one to use.

For Salus, the only way I can see of doing it is matching on the device name, e.g. "SP600".  If this is the only way, I'll have to make some additions to the base OTA functions to allow it to work like that.

Does anyone have experience or ideas on this?  Are there any additional references I should be using?

**Comment by puddly** [comment]
Thanks!

Currently, the only context passed to the main `OTA` class when a device asks for a firmware image is just the manufacturer ID and image type:

https://github.com/zigpy/zigpy/blob/468b533eda9216dfc679acd6d542849206daa87d/zigpy/zcl/clusters/general.py#L1070-L1072

One way to get this to work is to propagate an additional (optional?) `device` argument into here as well, so your image provider has enough context to pick an image:

https://github.com/zigpy/zigpy/blob/468b533eda9216dfc679acd6d542849206daa87d/zigpy/ota/__init__.py#L117

**Comment by Adminiuga** [comment]
Wonder if firmware download module should be outside of zigpy at all. Then just download/refresh all images and put them into a folder for zigpy to pick

**Comment by davet2001** [comment]
Yes, this could work.

But then every HA user would automatically download all FW images from every vendor?  Perhaps this is not kind to the vendor servers.

I think you would still need a way to iterate through the list and download them (and in the case of Salus extract a tar.gz).

**Comment by MattWestb** [comment]
IKEA is using "custom scenes commands" on there remotes and they is being restored to default then doing OTA upgrade and being lost then resetting the device for paring it and ZHA can **sadly** not adding scenes (missing some ZCL 7 commands). 
So downgrading and upgrading IKEA lights you is getting the scene button working  on your lights :-))

**Comment by davet2001** [comment]
@puddly PR #839 created.

**Comment by Hedda** [comment]
> either by maintaining an external index file, like z2m,...

Would it be a bad idea to maintain and reference a such external index file in the zha-quirks / zha-device-handlers repository?

https://github.com/Koenkk/zigbee-OTA/blob/master/index.json

While off-topic for OTA, know that Z2M devs are considering a similar external index file for community OTW firmware, see:

https://github.com/Koenkk/Z-Stack-firmware/issues/310

**Comment by davet2001** [comment]
This would be fine by me. Probably could be generated by a script as it would need to be updated quite often.

Would it be one file per vendor or one big file?
