### ISSUE TITLE
Coordinator Backup not working on SONOFF Zigbee 3.0 USB Dongle Plus

### ISSUE THREAD

**Issue by end84** [zigpy/zigpy#841]
Hello,

i have a "SONOFF Zigbee 3.0 USB Dongle Plus" and tried to perform a Coordinator Backup with `sudo bellows -d /dev/ttyUSBX info` and `sudo bellows -d /dev/ttyUSBX -b 115200 info`

- Yes, Python 3.8 is installed
- I installed bellows with pip3.8
- Yey, i changed `/dev/ttyUSBX` to `/dev/ttyUSB0` (in my case)

![bellows](https://user-images.githubusercontent.com/93480829/139705682-1c30ef53-fcfb-46e5-ab73-d2758523cddf.png)

**Comment by puddly** [comment]
`bellows` is for Silicon Labs/EZSP coordinators. You have a Texas Instruments coordinator so use zigpy-znp: https://github.com/zigpy/zigpy-znp/blob/dev/TOOLS.md#network-backup
