### ISSUE TITLE
Soil Moisture measurment is missing

### ISSUE THREAD

**Issue by majkrzak** [zigpy/zigpy#843]
I've recently acquired a plant watering sensor.
https://github.com/smartboxchannel/Plant-Watering-Sensor-Zigbee
https://www.zigbee2mqtt.io/devices/EFEKTA_PWS.html

Sadly it only reports battery and temperature, but not the most important: Soil Moisture

What I see is that the cluster 0x408 is in the "TODO"
https://github.com/zigpy/zigpy/blob/fc8e923e2f2482810b9643c0b2bde149a56a1930/zigpy/zcl/clusters/measurement.py#L122

Should it be just added in the similar way as the other there?

**Comment by puddly** [comment]
You can find the appropriate cluster in [the ZCL v7 spec](https://github.com/Koenkk/zigbee-herdsman/blob/master/docs/Zigbee%20Cluster%20Library%20Specification%20v7.pdf), it'll show the cluster's attributes. I believe it's similar in structure to the surrounding clusters (min/max/tolerance and value attributes), if not identical.
