### ISSUE TITLE
get_model_info stopped working for devices not supporting multiple read attributes

### ISSUE THREAD

**Issue by lortiejp** [zigpy/zigpy#923]
The code in endpoint.py (lines: 178-187) doesn't work for devices that don't support multiple read attributes. The list (["manufacturer", "model"], ["manufacturer"], ["model"]) is expected to be iterated but it isn't. The code only calls self.basic.read_attributes one time with the first array of 2. (I don't know why that is, I suspect it has something to do with the await.) Putting a self.debug statement there, will prove it.

This has the effect of preventing all Zigbee devices that don't support multiple read attribute from being identified and properly paired in the zigbee network. (I don't know how many there are, but all my Sinope are like that.)

I suspect the problem was introduced with commit id: 78cefbca987a7188b556e189e58fb6348a67a4ab, where the loop was introduced.

A simple fix would be to query the values manufacturer and model one after the other. (I did that on my test instance and it worked.) It's not important (in my opinion) to absolutely get all these values in one multiple read attributes since it only happens at pairing time.

Thanks!

**Comment by lortiejp** [comment]
I'll post the debug log later, but I can say, as I sniffed the zigbee network, the device just doesn't answer. I see the packet containing the combined request being issued from the coordinator but no response from the device. The coordinator sends the packet three times. When I look at the log, I also see that it tries to send the combined packet three times. I never see a packet with the single attribute being sent afterwards. 
I think that at device identification time, the software should really just send two separate packets as this will always work with any device. Send one combined packet and two uncombined ones is just redundant anyways as the devices capable of answering to combined packets will also answer to the uncombined ones afterwards, anyways. 

I can submit a PR if you want for the code change I would propose if you think it'll be faster.

**Comment by MattWestb** [comment]
I have finding one tuya "magic spell" that looks like this in WS:
```
ZigBee Application Support Layer Data, Dst Endpt: 255, Src Endpt: 1
    Frame Control Field: Data (0x40)
        .... ..00 = Frame Type: Data (0x0)
        .... 00.. = Delivery Mode: Unicast (0x0)
        ..0. .... = Security: False
        .1.. .... = Acknowledgement Request: True
        0... .... = Extended Header: False
    Destination Endpoint: 255
    Cluster: Basic (0x0000)
    Profile: Home Automation (0x0104)
    Source Endpoint: 1
    Counter: 201
ZigBee Cluster Library Frame, Command: Read Attributes, Seq: 26
    Frame Control Field: Profile-wide (0x10)
        .... ..00 = Frame Type: Profile-wide (0x0)
        .... .0.. = Manufacturer Specific: False
        .... 0... = Direction: Client to Server
        ...1 .... = Disable Default Response: True
    Sequence Number: 26
    Command: Read Attributes (0x00)
    Attribute: Manufacturer Name (0x0004)
    Attribute: ZCL Version (0x0000)
    Attribute: Application Version (0x0001)
    Attribute: Model Identifier (0x0005)
    Attribute: Power Source (0x0007)
    Attribute: Unknown (0xfffe)
```
And the device is reporting back:
```
ZigBee Cluster Library Frame, Command: Read Attributes Response, Seq: 26
    Frame Control Field: Profile-wide (0x18)
        .... ..00 = Frame Type: Profile-wide (0x0)
        .... .0.. = Manufacturer Specific: False
        .... 1... = Direction: Server to Client
        ...1 .... = Disable Default Response: True
    Sequence Number: 26
    Command: Read Attributes Response (0x01)
    Status Record, String: _TZ3000_1obwwnmq
        Attribute: Manufacturer Name (0x0004)
        Status: Success (0x00)
        Data Type: Character String (0x42)
        String: _TZ3000_1obwwnmq
    Status Record, Uint8: 3
        Attribute: ZCL Version (0x0000)
        Status: Success (0x00)
        Data Type: 8-Bit Unsigned Integer (0x20)
        Uint8: 3 (0x03)
    Status Record, Uint8: 70
        Attribute: Application Version (0x0001)
        Status: Success (0x00)
        Data Type: 8-Bit Unsigned Integer (0x20)
        Uint8: 70 (0x46)
    Status Record, String: TS011F
        Attribute: Model Identifier (0x0005)
        Status: Success (0x00)
        Data Type: Character String (0x42)
        String: TS011F
    Status Record
        Attribute: Power Source (0x0007)
        Status: Success (0x00)
        Data Type: 8-Bit Enumeration (0x30)
        Power Source: Mains (single phase) (0x01)
    Status Record, Enum8: 0
        Attribute: Unknown (0xfffe)
        Status: Success (0x00)
        Data Type: 8-Bit Enumeration (0x30)
        Uint8: 0 (0x00)
```
That is needed doing the same thing in ZHA for getting the LIDL power stripe using all 3 endpoints for the plugs.

I cant testing if its working then my strips is on original firmware and is working OK but we need sending the same from the quirk then some one is getting it working.

So some device like and some other is not liking multiple attribute reading in one commands and very likely some must getting it then the device is in INIT mode and is not working if delaying them to long and the device is not in INIT mode.

**Comment by puddly** [comment]
> I think that at device identification time, the software should really just send two separate packets as this will always work with any device. 

This is just a logic bug introduced during the initialization rewrite, the old behavior was identical: https://github.com/zigpy/zigpy/blob/234afffff0ca8881165625dd565faf27e286ad9d/zigpy/endpoint.py#L180-L185

The goal is to perform basic initialization as fast as possible, since some end-devices devices to go to sleep very quickly and ZHA initialization can time out if done too late.

> I'll post the debug log later, but I can say, as I sniffed the zigbee network, the device just doesn't answer.

That is unexpected. It doesn't return any status code like `UNSUPPORTED_ATTRIBUTE`? That seems like the only way for the loop to not end up reading the model or manufacturer name.

**Comment by lortiejp** [comment]
> That is unexpected. It doesn't return any status code like UNSUPPORTED_ATTRIBUTE? That seems like the only way for the loop to not end up reading the model or manufacturer name.

I really don't know why but there's nothing coming out of device after it is sent. I'll do the test another time to see if I'm missing something. 

One thing that I see, though is that the for loop at line  178-187 of the current endpoint.py is ever only executing for the first array element. It's the real problem, then I think. Should it be an _async for_? I'm not familiar enough with asyncio programming yet. The code before was basically doing the same thing but outside of a loop, just one thing after the other.

**Comment by puddly** [comment]
> One thing that I see, though is that the for loop at line 178-187 of the current endpoint.py is ever only executing for the first array element.

There's no way to exit the loop so either:

 - it gets stuck on the first read and times out,
 - throws an error that zigpy doesn't handle,
 - or the device responds with `UNSUPPORTED_ATTRIBUTE` and this response gets cached, causing subsequent reads to just return that same value from the cache.

The debug log (or PCAP!) would clarify what's happening.

**Comment by lortiejp** [comment]
Hello again!
I joined the relevant parts of the log (I just grepped all zig lines to eliminate the clutter.).

I also include the wireshark capture file. The concerned device is ieee 50:0b:91:40:00:01:e7:d4 and gets network number 0x9a9c at join time. You will see at packet 2419 the first Read attributes request from the controler. Then, no response except broadcasts followed by two more read attributes with combined values (pkts 2562 and 2621). (I see retries in the log which must correspond to these two packets.)

Then nothing. The gui states that it's interrogating the device indefinitely... 

Somehow, when the device doesn't answer the three retries, the loop derails and never asks for the attributes individually.

[home-assistant-zig.log](https://github.com/zigpy/zigpy/files/8147116/home-assistant-zig.log)
[join-sinope.zip](https://github.com/zigpy/zigpy/files/8147117/join-sinope.zip)

**Comment by lortiejp** [comment]
Hello!
I can confirm that this fix works like a charm with the Sinope devices. Thanks a lot!

**Comment by Adminiuga** [comment]
What kind of Sinope device is this and how old? Do they offer any firmware updates?

**Comment by lortiejp** [comment]
I have thermostats (TH1400ZB) and dimmers (DM2500ZB) and they're pretty new and current. You can go on their site to see them. All of them have this problem. Sinope doesn't promote the use of these devices on other platform other than their's (Neviweb with a gt130). They still don't have a firmware upgrade that would fix this either. And frankly, I'm not sure how I would upgrade the devices as there's no OTA in zha for them either. For now, I prefer to use them in zha as their solution (Neviweb) needs a web connection to interact with them which is a total no-go for me.
