### ISSUE TITLE
Successful attribute writes are not written to the database

### ISSUE THREAD

**Issue by dmulcahey** [zigpy/zigpy#958]
Attribute reports are cached in the database when they are received. Successful attribute writes should also be cached to ensure that the attribute cache doesn't get out of sync.

**Comment by puddly** [comment]
It looks like this should already be happening (line 549):

https://github.com/zigpy/zigpy/blob/3857bfe3e7bdafffb0850c8171e06598471cdaba/zigpy/zcl/__init__.py#L531-L556
