### ISSUE TITLE
[REQUEST] Ubisys OTA provider for Ubisys branded Zigbee devices

### ISSUE THREAD

**Issue by Hedda** [zigpy/zigpy#988]
Posting as a dedicated feature request as someone posted this question in Home Assistant community forum after asking Ubisys:

https://community.home-assistant.io/t/zha-ubisys-ota-updates-firmware-is-available-on-their-website/290430

Ubisys support sent this reply to user question about Zigbee OTA support in ZHA and other open source Zigbee implementations:

> **_We do in fact make the newst firmware available to the general public on our website, so a proper OTA server (e.g. Raspberry… ) can be used to distribute our update files easily._** 
>  
> **_Here´s the link:_** http://www.ubisys.de/en/support/firmware/
> 
> **_As far as I´m aware of we neither have we ourselves approached, nor have we been approached by ZHA, regarding 3rd party OTA files being supported, sorry!_** 
> 
> **_You could get in touch with them as well, maybe that´ll create a ticket on their side - initiating first contact with us :wink:_**
> 
> **_I´ll also mention this in our next team meeting!_**

For reference, Zigbee2MQTT does already have a dedicated OTA provider for Ubisys in zigbee-herdsman-converters:

https://github.com/Koenkk/zigbee-herdsman-converters/tree/master/lib/ota

https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/lib/ota/ubisys.js

Information for other end-end users and new developers wondering what is needed for this to be integrated into zigpy and ZHA:

ZHA does have support download code for third-party OTA providers however someone need to code each download source:

https://www.home-assistant.io/integrations/zha#ota-firmware-updates

https://github.com/zigpy/zigpy#zigbee-device-ota-updates

So what is needed is for a Python developer to submit download code with URLs for each Zigbee OTA provider, see the code:

https://github.com/zigpy/zigpy/tree/dev/zigpy/ota

https://github.com/zigpy/zigpy/blob/dev/zigpy/ota/provider.py

Since zigpy is free and open source software such code is usually submitted by either manufacturers themselves or an independent developer who own such specific products and therefor have personal interest to code OTA code to zigpy.

However I have not read about any existing developers expressing interest in working on adding OTA provider to zigpy for Ubisys, which probably means that they do own any Ubisys or do not have time to priotize coding this over other things:

https://github.com/zigpy/zigpy/issues?q=ota

But FYI, note that end-users can still flash those with ZHA if enable OTA and then manually copy OTA file(s) to directory, read:

[https://www.home-assistant.io/integrations/zha#ota-firmware-updates](https://www.home-assistant.io/integrations/zha#ota-firmware-updates)

[https://github.com/zigpy/zigpy/wiki/OTA-Device-Firmware-Updates](https://github.com/zigpy/zigpy/wiki/OTA-Device-Firmware-Updates)

PS:  In a related question wondering if Ubisys are aware of Home Assistant's "**_Works with Home Assistant_**" partner program with its matching "**_Works via Zigbee with Home Assistant_**" compatibility badges and if they would consider joining it?

https://www.home-assistant.io/blog/2022/07/12/partner-program/

There it says "**_Works with Home Assistant partners are expected to provide firmware updates via user-friendly services provided by Home Assistant_**" under **_Responsibilities_** in a section there called "**_Provide easy firmware updates_**".

https://partner.home-assistant.io/

"_**There are manufacturers that are creating products that integrate into Home Assistant using standards like Z-Wave, Zigbee, or Matter (soon). In these cases, the integration is maintained by the Home Assistant community and Nabu Casa. These companies can still become a member of the Works with Home Assistant program but are relieved from integration maintenance.**_"

"_**With Home Assistant we are always working on educating our users about preferring local control and open standards when acquiring new products. This is also reflected in the “Works with Home Assistant” badges.**_"

![image](https://user-images.githubusercontent.com/6320001/196415473-f3020a0c-3a6d-407c-838f-4cf6cc5fa466.png)

So far they have only announced one other company which makes and sells Zigbee devices that joined their partner program:

https://www.home-assistant.io/blog/2022/10/13/third-reality-partner/

This relates to zigpy as it may imply some commitment from companies to help with both OTA updates and ZHA Device Handlers.

https://www.home-assistant.io/integrations/zha#ota-firmware-updates

https://github.com/zigpy/zigpy/blob/dev/README.md#zigbee-device-ota-updates

https://www.home-assistant.io/integrations/zha#zha-exception-and-deviation-handling

https://github.com/zigpy/zha-device-handlers

https://github.com/zigpy/zha-device-handlers/blob/dev/README.md

**Comment by Hedda** [comment]
FYI, I got this reply from Ubisys when I asked about a Ubisys Zigbee OTA provider in zigpy for Home Assistant's ZHA integration:

> "**_Hi,_**
> 
> **_Currently we do not have any development resources available, but already have agreed to take care of this topic._**
> 
> **_However, it is difficult to give a timeline, but we will try to work on it in the short term and keep you posted._**
> 
> **_Kind regards_**
> 
> **_Ubisys Support Team_**"

**Comment by Hedda** [comment]
FYI, puddly has just now added a new feature to the "[zigpy-cli](https://github.com/zigpy/zigpy-cli)" tool that manufacturers can use to produce a skeleton JSON index from a given set of OTA files, and that way make sure manufacturers OTA files are correctly-structured so that they will be compatible with zigpy out-of-the-box. See the README.md for the "[zigpy-cli](https://github.com/zigpy/zigpy-cli)" tool. See:

https://github.com/zigpy/zigpy-cli/blob/dev/README.md#ota

and

https://github.com/zigpy/zigpy-cli/blob/dev/README.md#generate-ota-index-files

PS: puddly mentioned when adding that feature for generating OTA index files via zigpy-cli was done in preparation for some OTA rewrites in the main zippy library that he is planning to do.

**Comment by Hedda** [comment]
FYI, puddly is now working on supporting "Generic OTA providers" for zigpy via this new JSON format schema:

https://github.com/zigpy/zigpy/wiki/OTA-Information-for-Manufacturers

  "**_This allows for new providers to be added to zigpy without extra code. This also allows for manufacturers to distribute test feed URLs to customers without deploying them globally._**"

This feature will be introduced via this new pull request that is still a work-in-progress ->  https://github.com/zigpy/zigpy/pull/1165

**Comment by Hedda** [comment]
FYI, “**_Manufacturer OTA Firmware Update Support_**” (also referred to as “**_Generic OTA providers_**”) should now be available for use in ZHA as that was added with zigpy 0.56.3 release and that was very recently bumped in Home Assistant core version 2023.8.1(?)

https://github.com/zigpy/zigpy/pull/1165

This new feature in zigpy (and ZHA) should allow for new OTA providers to be added to zigpy (and ZHA) without extra code, which in turn also allows both manufacturers (and end-users) to distribute test feed URLs to customers without deploying them globally.

https://github.com/zigpy/zigpy/wiki/OTA-Information-for-Manufacturers

PS: Again, puddly also added a new feature to the "[zigpy-cli](https://github.com/zigpy/zigpy-cli)" tool that manufacturers can use to produce/generate a skeleton index from a given set of OTA files, and that way makes sure manufacturers OTA files are correctly-structured so that they will be compatible with this new JSON format for zigpy OTA providers out-of-the-box. Check out the README.md for the "[zigpy-cli](https://github.com/zigpy/zigpy-cli)" (zigpy CLI tool) -> [https://github.com/zigpy/zigpy-cli/blob/dev/README.md#generate-ota-index-files](https://github.com/zigpy/zigpy-cli/blob/dev/README.md#generate-ota-index-files)

**Comment by Hedda** [comment]
More relevant now with https://github.com/zigpy/zigpy/pull/1340

**Comment by puddly** [comment]
https://github.com/zigpy/zigpy/issues/1060#issuecomment-1951415531
